#!/bin/bash
set -e -x

source $(dirname $0)/version

cd $(dirname $0)/..

mkdir -p bin
LINKFLAGS="-buildid= -X main.VERSION=$VERSION -s -w"
[ "$(uname)" != "Darwin" ] && LINKFLAGS="$LINKFLAGS -extldflags -static"
CGO_ENABLED=0 go build -trimpath -buildvcs=false -a -tags 'static netgo' -ldflags "$LINKFLAGS" -o bin/authentication-service
