#!/bin/bash
set -e -x

cd $(dirname $0)/..

echo Running tests

PACKAGES="./..."

RACE_FLAGS=()
if [ "${ARCH:-amd64}" = "amd64" ]; then
    RACE_FLAGS=(-race)
fi

CGO_ENABLED=1 CC="${CC:-gcc}" go test -mod=vendor "${RACE_FLAGS[@]}" -cover -tags=test ${PACKAGES}
