#!/bin/bash
set -e -x

cd $(dirname $0)/..

echo Running tests

PACKAGES=". $(find . -name '*.go' | xargs -I{} dirname {} |  cut -f2 -d/ | sort -u | grep -Ev '(^\.$|.git|vendor|bin)' | sed -e 's!^!./!' -e 's!$!/...!')"

RACE_FLAGS=()
if [ "${ARCH:-amd64}" = "amd64" ]; then
    RACE_FLAGS=(-race)
fi

CGO_ENABLED=1 CC="${CC:-gcc}" go test "${RACE_FLAGS[@]}" -cover -tags=test ${PACKAGES}
